#!/bin/bash

echo "Installing BAMToGASV and GASV..."
mkdir bin
ant

echo "Installing GASV-CC..."
g++ -O2 -w src/gasvPro/GASV-cc.cpp -o bin/GASV-CC

echo "Installing GASVPro-graph..."
g++ -O2 -w src/gasvPro/GASVPro-graph.cpp -o bin/GASVPro-graph

echo "Installing GASVPro-mcmc..."
g++ -O2 -w src/gasvPro/GASVPro-mcmc.cpp -o bin/GASVPro-mcmc

echo "Installation complete. Check for errors." 	
